##Kafka Stream Configuration
spring.cloud.stream:
  function:
    definition: domainProcessor #Function Name in configuration
  bindings:
    domainProcessor-in-0:
      destination: web-domains #Topic Name In
    domainProcessor-out-0:
      destination: active.web-domains #TopicName out

  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group_id
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer

      domainProcessor-out-0:
        producer:
          bootstrap-servers: localhost:9092
            #key-serializer: org.apache.kafka.common.serialization.StringSerializer
            #value-serializer: org.apache.kafka.common.serialization.JsonSerializer

    binder:
      #Broker info
      brokers:
        - localhost:9091
        - localhost:9092