##Kafka Stream Configuration
spring.cloud.stream:
  function:
    definition: domainService #Function Name in configuration
  bindings:
    domainService-in-0:
      destination: active.web-domains #Topic Name In
      ##Abbiamo solamente topic in entrata e le info
      ##vengono consumate senza inserirle all'interno di
      ##un altro topic!

  kafka:
    bindings:
      domainService-in-0:
        consumer:
          bootstrap-servers: localhost:9092
          group-id: group_id
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer

    binder:
      #Broker info
      brokers:
        - localhost:9091
        - localhost:9092